import "./globals.css"
import type { Metadata } from "next"
import localFont from "next/font/local"

import Footer from "@/components/Footer"
import { Toaster } from "react-hot-toast"
import { ClerkProvider } from "@clerk/nextjs"
import ConvexClientProvider from "@/components/providers/ConvexClientProvider"

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
})
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
})

export const metadata: Metadata = {
	title: "Code Craft Pooh",
	description: "Generated by Hoapooh",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-b from-gray-900 to-gray-950 text-gray-100 flex flex-col`}
				>
					<ConvexClientProvider>{children}</ConvexClientProvider>

					<Footer />

					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	)
}
